name: Push to main

on:
  push:
    branches:
      - "main"

  workflow_dispatch:


jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('package.lock.json') }}
      - run: npm ci

  build:
    needs: [dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('package.lock.json') }}
      - run: npm run build

  lint:
    needs: [dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('package.lock.json') }}
      - run: npm run lint

  test:
    needs: [dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('package.lock.json') }}
      - run: npm run test
