name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('package.lock.json') }}
      - run: npm ci

  build:
    needs: [dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('package.lock.json') }}
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          path: dist
          name: dist

  lint:
    needs: [dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('package.lock.json') }}
      - run: npm run lint

  test:
    needs: [dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('package.lock.json') }}
      - run: npm run test

  publish:
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - run: cd dist/packages/empiricist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
